version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel_app
    volumes:
      - .:/var/www/html
    ports:
      - '8000:8000'
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=
    depends_on:
      - mysql
    command: php -S 0.0.0.0:8000 -t public
    networks:
      - laravel-network

  vite:
    image: node:20
    container_name: laravel_vite
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - '5173:5173'
    command: >
      sh -c "npm install && npm run dev -- --host 0.0.0.0"
    depends_on:
      - app
    networks:
      - laravel-network

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    environment:
      - MYSQL_DATABASE=college
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - laravel-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: laravel_phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=
    ports:
      - '8080:80'
    depends_on:
      - mysql
    networks:
      - laravel-network

volumes:
  mysql-data:

networks:
  laravel-network:
    driver: bridge
