services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    image: laravel-app
    container_name: laravel_app
    volumes:
      - ./:/var/www/html:delegated
    ports:
      - '8000:8000'
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_URL: http://82.115.49.244:8000
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: '3306'
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    platform: linux/arm64/v8
    container_name: laravel_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: college
      MYSQL_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - '127.0.0.1:3306:3306'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-proot']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - laravel

  phpmyadmin:
    image: lscr.io/linuxserver/phpmyadmin:latest
    container_name: laravel_phpmyadmin
    environment:
      PUID: '1000'
      PGID: '1000'
      TZ: Asia/Qostanay
      PMA_HOST: mysql
      PMA_PORT: '3306'
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 512M
    ports:
      - '8080:80'
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - laravel

  vite:
    image: node:20
    container_name: laravel_vite
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:delegated
    ports:
      - "5173:5173"
    command: >
      bash -lc "npm ci && npm run dev -- --host 0.0.0.0"
    networks:
      - laravel
    

volumes:
  mysql-data:

networks:
  laravel:
    driver: bridge
